### ISSUE TITLE
Image Missing

### ISSUE THREAD

**Issue by zl930216** [bborja/modd#1]
Hi,
I was trying to run modd2_evaluate_all_sequence_raw, but an error occured.
It seems all the images mentioned **from line 19 to line 34 of perform_evaluation_on_sequence.m** are not found.
I've downloaded all files shared and put them to right position according to the content of modd2_evaluate_all_sequence_raw.m

**Comment by bborja** [comment]
The paths have been updated now. Thanks for notifying me.
